### ISSUE TITLE
Shared stash items ignored

### ISSUE THREAD

**Issue by Henney** [Tedris/PlugyTools#1]
All characters are being analyzed properly, but shared stash items are ignored (where I place all my grail items not currently in use). I might try to make a pull request if I have time to fix it myself.

Great tool otherwise!

**Comment by Henney** [comment]
Upon closer inspection, part of the issue seems to be signed byte values (I have 200 shared stash pages, so byte 6 in the .sss file is 0xc8, which is treated as -56 rather than 200). Should be easily fixable by reading all 4 bytes with getHexStringFromRange and getDecimalFromSubstring instead of just the one byte.

However, some items still seem to be ignored. Maybe that should be opened as a separate issue since I don't know the cause.

**Comment by Tedris** [comment]
Sorry it took so long!  Thanks for the change!
